version: "3.9"
services:
  jpb-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      JPB_PERSISTENCE_MODE: "ms"
      JPB_MODEL_INITIALIZE: "true"
      JPB_MODEL_WAREHOUSE-COUNT: "10"
      JPB_MODEL_FULL-SCALE: "true"
      JPB_MS_STORAGE_DIR: "storage"
    volumes:
      - microstream_storage:/home/jpb/${JPB_MS_STORAGE_DIR}
volumes:
  microstream_storage:
