version: "2.4"
services:
  wss-server:
    container_name: "wss-server"
    build:
      context: .
      dockerfile: Dockerfile-ms-sync
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Berlin
      - SPRING_PROFILES_ACTIVE=prod
      - WSS_MODEL_INITIALIZE=true
      - WSS_MODEL_WAREHOUSE_COUNT=5
      - WSS_MODEL_FULL_SCALE=true
      - WSS_MS_STORAGE_DIR=storage
      - JAVA_OPTS=-Xmx14G
    volumes:
      - ms_data:/home/wss/storage
    cpu_count: 4
    mem_reservation: 12g
    mem_limit: 14g
volumes:
  ms_data:
