version: "3.7"
services:
  jpb-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      JPB_PERSISTENCE_MODE: "ms"
      JPB_MODEL_INITIALIZE: "true"
      JPB_MODEL_WAREHOUSE-COUNT: "10"
      JPB_MODEL_FULL-SCALE: "true"
      JPB_MS_STORAGE_DIR: "storage"
      JAVA_OPTS: "-Xmx2G"
    volumes:
      - microstream_storage:/home/jpb/storage
volumes:
  microstream_storage:
